version: '3'

services:
  resque:
    container_name: resque-ui
    build:
      context: .
    restart: unless-stopped
    networks:
      - resque
    ports:
      - "5600:5678"
    environment:
      - RESQUE_WEB_HOST=redis
      - RESQUE_WEB_PORT=6379
      - RESQUE_WEB_DB=0